insert into public.sea_critters (
    id,
    display_name,
    rarity,
    sell_value,
    asset_name,
    sort_order,
    drop_weight,
    is_enabled
)
values
    ('bass', 'Bass', 'common', 1, 'Fish_Bass', 1, 100, true),
    ('crab', 'Crab', 'common', 1, 'SeaShellfish_Crab_Red', 2, 100, true),
    ('halibut', 'Halibut', 'common', 1, 'Fish_Halibut', 3, 100, true),
    ('herring', 'Herring', 'common', 1, 'Fish_Herring', 4, 100, true),
    ('salmon', 'Salmon', 'rare', 2, 'Fish_Salmon', 5, 25, true),
    ('shrimp', 'Shrimp', 'common', 1, 'SeaShellfish_Shrimp_Pink', 6, 100, true),
    ('tuna', 'Tuna', 'ultra_rare', 3, 'Fish_Tuna', 7, 5, true),
    ('anglerfish', 'Anglerfish', 'rare', 2, 'DeepSeaFish_AnglerFish', 8, 25, true),
    ('butterflyfish', 'Butterflyfish', 'rare', 2, 'TropicalFish_ButterflyFish', 9, 25, true),
    ('clownfish', 'Clownfish', 'rare', 2, 'TropicalFish_Clownfish_Orange', 10, 25, true),
    ('eel', 'Eel', 'rare', 2, 'Fish_Eel', 11, 25, true),
    ('jellyfish', 'Jellyfish', 'rare', 2, 'SeaInvertebrate_Jellyfish_Blue', 12, 25, true),
    ('lionfish', 'Lionfish', 'rare', 2, 'TropicalFish_LionFish', 13, 25, true),
    ('lobster', 'Lobster', 'rare', 2, 'SeaShellfish_Lobster_Red', 14, 25, true),
    ('marlin', 'Marlin', 'rare', 2, 'Fish_MarlinSwordfish', 15, 25, true),
    ('nautilus', 'Nautilus', 'rare', 2, 'SeaShellfish_Nautilus', 16, 25, true),
    ('octopus', 'Octopus', 'rare', 2, 'SeaInvertebrate_Octopus_Orange', 17, 25, true),
    ('pufferfish', 'Pufferfish', 'rare', 2, 'Fish_PufferFish', 18, 25, true),
    ('seahorse', 'Seahorse', 'rare', 2, 'Fish_SeaHorse_Yellow', 19, 25, true),
    ('squid', 'Squid', 'rare', 2, 'SeaInvertebrate_Squid_Pink', 20, 25, true),
    ('stingray', 'Stingray', 'rare', 2, 'Fish_StingRay', 21, 25, true),
    ('turtle', 'Turtle', 'rare', 2, 'SeaReptile_Turtle', 22, 25, true),
    ('blobfish', 'Blobfish', 'ultra_rare', 5, 'DeepSeaFish_BlobFish', 23, 5, true),
    ('blue_lobster', 'Blue Lobster', 'ultra_rare', 5, 'SeaShellfish_Lobster_Blue', 24, 5, true),
    ('dolphin', 'Dolphin', 'ultra_rare', 5, 'SeaMammal_Dolphin', 25, 5, true),
    ('great_white', 'Great White', 'ultra_rare', 5, 'Fish_GreatWhiteShark', 26, 5, true),
    ('hammerhead', 'Hammerhead', 'ultra_rare', 5, 'Fish_HammerHeadShark', 27, 5, true),
    ('narwhal', 'Narwhal', 'ultra_rare', 5, 'SeaMammal_Narwhale', 28, 5, true),
    ('orca', 'Orca', 'ultra_rare', 5, 'SeaMammal_Orca', 29, 5, true),
    ('sunfish', 'Sunfish', 'ultra_rare', 5, 'Fish_Sunfish', 30, 5, true),
    ('whale', 'Whale', 'ultra_rare', 5, 'SeaMammal_Whale', 31, 5, true),
    ('whale_shark', 'Whale Shark', 'ultra_rare', 5, 'Fish_WhaleShark', 32, 5, true)
on conflict (id) do update
set display_name = excluded.display_name,
    rarity = excluded.rarity,
    sell_value = excluded.sell_value,
    asset_name = excluded.asset_name,
    sort_order = excluded.sort_order,
    drop_weight = excluded.drop_weight,
    is_enabled = excluded.is_enabled;

notify pgrst, 'reload schema';
